In [89]:
import pandas as pd 
import numpy as np
import lightgbm as lgb 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss

## 一，准备数据

In [90]:
df_train= pd.read_csv("data/train.csv")
df_test= pd.read_csv("data/test.csv")
df_train

,Id,Label,I1,I2,I3,I4,I5,I6,I7,I8,...,C17,C18,C19,C20,C21,C22,C23,C24,C25,C26
0,10000743,1,1.0,0,1.0,NaN,227.0,1.0,173.0,18.0,...,3486227d,e88ffc9d,c393dc22,b1252a9d,57c90cd9,NaN,bcdee96c,4d19a3eb,cb079c2d,456c12a0
1,10000159,1,4.0,1,1.0,2.0,27.0,2.0,4.0,2.0,...,07c540c4,92555263,NaN,NaN,242bb710,NaN,3a171ecb,72c78f11,NaN,NaN
2,10001166,1,0.0,806,NaN,NaN,1752.0,142.0,2.0,0.0,...,07c540c4,25c88e42,21ddcdc9,b1252a9d,a0136dd2,NaN,32c7478e,8fc66e78,001f3601,f37f3967
3,10000318,0,2.0,-1,42.0,14.0,302.0,38.0,25.0,38.0,...,e5ba7672,5aed7436,21ddcdc9,b1252a9d,c3abeb21,NaN,423fab69,1793a828,e8b83407,5cef228f
4,10000924,1,0.0,57,2.0,1.0,2891.0,2.0,35.0,1.0,...,e5ba7672,642f2610,1d1eb838,b1252a9d,1640d50b,ad3062eb,423fab69,45ab94c8,2bf691b1,c84c4aec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,10000835,0,NaN,8,1.0,1.0,43.0,NaN,0.0,1.0,...,1e88c74f,fc35e8fe,NaN,NaN,a02708ad,c9d4222a,c3dc6cef,502f2493,NaN,NaN
1595,10001216,0,8.0,2,20.0,8.0,36.0,9.0,8.0,10.0,...,e5ba7672,5aed7436,21ddcdc9,b1252a9d,eea796be,NaN,3a171ecb,1793a828,e8b83407,5cef228f
1596,10001653,0,0.0,1,2.0,12.0,4877.0,140.0,13.0,34.0,...,e5ba7672,2b0a9d11,NaN,NaN,7453e535,NaN,dbb486d7,906e72ec,NaN,NaN
1597,10000559,0,NaN,2,NaN,1.0,1972.0,NaN,0.0,1.0,...,e5ba7672,817481a8,NaN,NaN,e4244d7f,c9d4222a,c7dc6720,60efe6e6,NaN,NaN
1598,10000684,1,NaN,34,3.0,4.0,NaN,NaN,0.0,4.0,...,2005abd1,1cdbd1c5,NaN,NaN,288eaded,c9d4222a,bcdee96c,8fc66e78,NaN,NaN

In [91]:
df_train.drop(['Id'], axis = 1, inplace = True)
df_test.drop(['Id'], axis = 1, inplace = True)

In [92]:
df_train

,Label,I1,I2,I3,I4,I5,I6,I7,I8,I9,...,C17,C18,C19,C20,C21,C22,C23,C24,C25,C26
0,1,1.0,0,1.0,NaN,227.0,1.0,173.0,18.0,50.0,...,3486227d,e88ffc9d,c393dc22,b1252a9d,57c90cd9,NaN,bcdee96c,4d19a3eb,cb079c2d,456c12a0
1,1,4.0,1,1.0,2.0,27.0,2.0,4.0,2.0,2.0,...,07c540c4,92555263,NaN,NaN,242bb710,NaN,3a171ecb,72c78f11,NaN,NaN
2,1,0.0,806,NaN,NaN,1752.0,142.0,2.0,0.0,50.0,...,07c540c4,25c88e42,21ddcdc9,b1252a9d,a0136dd2,NaN,32c7478e,8fc66e78,001f3601,f37f3967
3,0,2.0,-1,42.0,14.0,302.0,38.0,25.0,38.0,90.0,...,e5ba7672,5aed7436,21ddcdc9,b1252a9d,c3abeb21,NaN,423fab69,1793a828,e8b83407,5cef228f
4,1,0.0,57,2.0,1.0,2891.0,2.0,35.0,1.0,137.0,...,e5ba7672,642f2610,1d1eb838,b1252a9d,1640d50b,ad3062eb,423fab69,45ab94c8,2bf691b1,c84c4aec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,0,NaN,8,1.0,1.0,43.0,NaN,0.0,1.0,1.0,...,1e88c74f,fc35e8fe,NaN,NaN,a02708ad,c9d4222a,c3dc6cef,502f2493,NaN,NaN
1595,0,8.0,2,20.0,8.0,36.0,9.0,8.0,10.0,8.0,...,e5ba7672,5aed7436,21ddcdc9,b1252a9d,eea796be,NaN,3a171ecb,1793a828,e8b83407,5cef228f
1596,0,0.0,1,2.0,12.0,4877.0,140.0,13.0,34.0,136.0,...,e5ba7672,2b0a9d11,NaN,NaN,7453e535,NaN,dbb486d7,906e72ec,NaN,NaN
1597,0,NaN,2,NaN,1.0,1972.0,NaN,0.0,1.0,14.0,...,e5ba7672,817481a8,NaN,NaN,e4244d7f,c9d4222a,c7dc6720,60efe6e6,NaN,NaN
1598,1,NaN,34,3.0,4.0,NaN,NaN,0.0,4.0,14.0,...,2005abd1,1cdbd1c5,NaN,NaN,288eaded,c9d4222a,bcdee96c,8fc66e78,NaN,NaN

In [93]:
df_test['Label'] = -1
df_test

,I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,...,C18,C19,C20,C21,C22,C23,C24,C25,C26,Label
0,NaN,-1,NaN,NaN,8020.0,26.0,6.0,0.0,80.0,NaN,...,7119e567,1d04f4a4,b1252a9d,d5f54153,NaN,32c7478e,a9d771cd,c9f3bea7,0a47000d,-1
1,NaN,-1,NaN,NaN,17881.0,9.0,8.0,0.0,0.0,NaN,...,51369abb,NaN,NaN,d4b6b7e8,NaN,32c7478e,37821b83,NaN,NaN,-1
2,0.0,0,2.0,13.0,2904.0,104.0,1.0,3.0,100.0,0.0,...,bd17c3da,966f1c31,a458ea53,1d1393f4,ad3062eb,32c7478e,3fdb382b,010f6491,49d68486,-1
3,0.0,1471,51.0,4.0,1573.0,63.0,1.0,4.0,13.0,0.0,...,1f9656b8,21ddcdc9,b1252a9d,602ce342,NaN,3a171ecb,1793a828,e8b83407,70b6702c,-1
4,0.0,16,9.0,17.0,2972.0,621.0,13.0,42.0,564.0,0.0,...,87c6f83c,NaN,NaN,bf8efd4c,c9d4222a,423fab69,f96a556f,NaN,NaN,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,1.0,0,1.0,NaN,149.0,5.0,1.0,0.0,0.0,1.0,...,5aed7436,d16737e3,a458ea53,edc49a33,NaN,93bad2c0,3fdb382b,e8b83407,80dd0a5b,-1
396,NaN,-1,NaN,NaN,NaN,NaN,0.0,0.0,6.0,NaN,...,5162930e,NaN,NaN,12965bb8,NaN,32c7478e,71292dbb,NaN,NaN,-1
397,0.0,300,4.0,NaN,4622.0,25.0,20.0,6.0,55.0,0.0,...,a78bd508,21ddcdc9,5840adea,c2a93b37,NaN,3a171ecb,1793a828,e8b83407,2fede552,-1
398,1.0,1,2.0,1.0,5.0,1.0,1.0,1.0,1.0,1.0,...,a1d0cc4f,c68db44a,a458ea53,3b1ae854,NaN,32c7478e,57e2c6c9,1575c75f,7132fed8,-1
399,NaN,2,NaN,NaN,36144.0,NaN,NaN,36.0,NaN,NaN,...,7b49e3d2,NaN,NaN,dfcfc3fa,NaN,423fab69,aee52b6f,NaN,NaN,-1

In [94]:
data = pd.concat([df_train, df_test])
data = data.fillna(-1)
data

,Label,I1,I2,I3,I4,I5,I6,I7,I8,I9,...,C17,C18,C19,C20,C21,C22,C23,C24,C25,C26
0,1,1.0,0,1.0,-1.0,227.0,1.0,173.0,18.0,50.0,...,3486227d,e88ffc9d,c393dc22,b1252a9d,57c90cd9,-1,bcdee96c,4d19a3eb,cb079c2d,456c12a0
1,1,4.0,1,1.0,2.0,27.0,2.0,4.0,2.0,2.0,...,07c540c4,92555263,-1,-1,242bb710,-1,3a171ecb,72c78f11,-1,-1
2,1,0.0,806,-1.0,-1.0,1752.0,142.0,2.0,0.0,50.0,...,07c540c4,25c88e42,21ddcdc9,b1252a9d,a0136dd2,-1,32c7478e,8fc66e78,001f3601,f37f3967
3,0,2.0,-1,42.0,14.0,302.0,38.0,25.0,38.0,90.0,...,e5ba7672,5aed7436,21ddcdc9,b1252a9d,c3abeb21,-1,423fab69,1793a828,e8b83407,5cef228f
4,1,0.0,57,2.0,1.0,2891.0,2.0,35.0,1.0,137.0,...,e5ba7672,642f2610,1d1eb838,b1252a9d,1640d50b,ad3062eb,423fab69,45ab94c8,2bf691b1,c84c4aec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,-1,1.0,0,1.0,-1.0,149.0,5.0,1.0,0.0,0.0,...,d4bb7bd8,5aed7436,d16737e3,a458ea53,edc49a33,-1,93bad2c0,3fdb382b,e8b83407,80dd0a5b
396,-1,-1.0,-1,-1.0,-1.0,-1.0,-1.0,0.0,0.0,6.0,...,2005abd1,5162930e,-1,-1,12965bb8,-1,32c7478e,71292dbb,-1,-1
397,-1,0.0,300,4.0,-1.0,4622.0,25.0,20.0,6.0,55.0,...,8efede7f,a78bd508,21ddcdc9,5840adea,c2a93b37,-1,3a171ecb,1793a828,e8b83407,2fede552
398,-1,1.0,1,2.0,1.0,5.0,1.0,1.0,1.0,1.0,...,d4bb7bd8,a1d0cc4f,c68db44a,a458ea53,3b1ae854,-1,32c7478e,57e2c6c9,1575c75f,7132fed8
399,-1,-1.0,2,-1.0,-1.0,36144.0,-1.0,-1.0,36.0,-1.0,...,e5ba7672,7b49e3d2,-1,-1,dfcfc3fa,-1,423fab69,aee52b6f,-1,-1

## 二，处理数据

In [95]:
data.columns

Index(['Label', 'I1', 'I2', 'I3', 'I4', 'I5', 'I6', 'I7', 'I8', 'I9', 'I10',
       'I11', 'I12', 'I13', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8',
       'C9', 'C10', 'C11', 'C12', 'C13', 'C14', 'C15', 'C16', 'C17', 'C18',
       'C19', 'C20', 'C21', 'C22', 'C23', 'C24', 'C25', 'C26'],
      dtype='object')

In [96]:
continuous_feature=list(data.columns)[1:14]
print(continuous_feature)

['I1', 'I2', 'I3', 'I4', 'I5', 'I6', 'I7', 'I8', 'I9', 'I10', 'I11', 'I12', 'I13']

In [97]:
category_feature = list(data.columns)[14:]
print(category_feature)

['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13', 'C14', 'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21', 'C22', 'C23', 'C24', 'C25', 'C26']

In [98]:
for col in category_feature:
    onehot_feats = pd.get_dummies(data[col], prefix = col)
    data.drop([col], axis = 1, inplace = True)
    data = pd.concat([data, onehot_feats], axis = 1)
data

,Label,I1,I2,I3,I4,I5,I6,I7,I8,I9,...,C26_fb7edec8,C26_fbe10aa8,C26_fcd456fa,C26_fcd5a3f4,C26_fd6ccd1e,C26_fdd86175,C26_fe7d4d4a,C26_ff2cdc2b,C26_ff86d5e0,C26_ffc123e9
0,1,1.0,0,1.0,-1.0,227.0,1.0,173.0,18.0,50.0,...,0,0,0,0,0,0,0,0,0,0
1,1,4.0,1,1.0,2.0,27.0,2.0,4.0,2.0,2.0,...,0,0,0,0,0,0,0,0,0,0
2,1,0.0,806,-1.0,-1.0,1752.0,142.0,2.0,0.0,50.0,...,0,0,0,0,0,0,0,0,0,0
3,0,2.0,-1,42.0,14.0,302.0,38.0,25.0,38.0,90.0,...,0,0,0,0,0,0,0,0,0,0
4,1,0.0,57,2.0,1.0,2891.0,2.0,35.0,1.0,137.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,-1,1.0,0,1.0,-1.0,149.0,5.0,1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
396,-1,-1.0,-1,-1.0,-1.0,-1.0,-1.0,0.0,0.0,6.0,...,0,0,0,0,0,0,0,0,0,0
397,-1,0.0,300,4.0,-1.0,4622.0,25.0,20.0,6.0,55.0,...,0,0,0,0,0,0,0,0,0,0
398,-1,1.0,1,2.0,1.0,5.0,1.0,1.0,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
399,-1,-1.0,2,-1.0,-1.0,36144.0,-1.0,-1.0,36.0,-1.0,...,0,0,0,0,0,0,0,0,0,0

In [99]:
train = data[data['Label'] != -1]
target = train.pop('Label')
test = data[data['Label'] == -1]
test.drop(['Label'], axis = 1, inplace = True)
print(train.shape,test.shape)
# print(train.head(5))

(1599, 13104) (400, 13104)

/Users/edz/anaconda3/envs/aicode/lib/python3.7/site-packages/pandas/core/frame.py:4167: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

## 三，模型训练

### GBDT模型

In [100]:
# 划分数据集
x_train, x_val, y_train, y_val = train_test_split(train, target, test_size = 0.2, random_state = 2020)

In [101]:
x_train.head(5)

,I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,...,C26_fb7edec8,C26_fbe10aa8,C26_fcd456fa,C26_fcd5a3f4,C26_fd6ccd1e,C26_fdd86175,C26_fe7d4d4a,C26_ff2cdc2b,C26_ff86d5e0,C26_ffc123e9
549,9.0,1,7.0,7.0,123.0,7.0,9.0,5.0,7.0,1.0,...,0,0,0,0,0,0,0,0,0,0
1379,-1.0,0,6.0,4.0,7198.0,92.0,5.0,4.0,303.0,-1.0,...,0,0,0,0,0,0,0,0,0,0
1306,-1.0,-1,2.0,3.0,6035.0,3.0,2.0,3.0,3.0,-1.0,...,0,0,0,0,0,0,0,0,0,0
23,-1.0,7,32.0,23.0,31645.0,41.0,15.0,14.0,24.0,-1.0,...,0,0,0,0,0,0,0,0,0,0
637,0.0,91,1.0,17.0,6171.0,463.0,19.0,30.0,449.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [102]:
print(x_train.shape,x_val.shape)

(1279, 13104) (320, 13104)

In [103]:
n_estimators = 32
num_leaves = 64
# 开始训练gbdt，使用32课树，每课树64个叶节点
model = lgb.LGBMRegressor(objective='binary',
                        subsample= 0.8,
                        min_child_weight= 0.5,
                        colsample_bytree= 0.7,
                        num_leaves=num_leaves,
                        learning_rate=0.05,
                        n_estimators=n_estimators,
                        random_state = 2020)
model.fit(x_train, y_train,
        eval_set = [(x_train, y_train), (x_val, y_val)],
        eval_names = ['train', 'val'],
        eval_metric = 'binary_logloss',
        verbose=0)

LGBMRegressor(colsample_bytree=0.7, learning_rate=0.05, min_child_weight=0.5,
              n_estimators=32, num_leaves=64, objective='binary',
              random_state=2020, subsample=0.8)

In [104]:
# 得到每一条训练数据落在了每棵树的哪个叶子结点上
# pred_leaf = True 表示返回每棵树的叶节点序号
gbdt_feats_train = model.predict(train, pred_leaf = True)
gbdt_feats_train

array([[ 7, 15,  1, ..., 25, 21, 37],
       [15, 17, 12, ..., 39, 30, 27],
       [30, 28, 46, ..., 34, 39, 37],
       ...,
       [27,  9, 34, ...,  5, 24, 34],
       [ 8,  5, 17, ..., 16,  7, 23],
       [33, 34, 39, ..., 21, 20, 40]], dtype=int32)

In [105]:
# 打印结果的 shape：
print(gbdt_feats_train.shape)
# 打印前5个数据：
print(gbdt_feats_train[:5])
#使用32棵树，且每棵树有64个叶节点;每个样本都得到32棵树叶节点序号。接下来输出的二维数组就展示了前5条训练数据落在了每棵树的哪个叶子结点上。

(1599, 32)
[[ 7 15  1 14 17  7  7 15 10 16 22 19  4 16  3 16 19 12  8  3 11 18  0 23
  22  3  8  3  6 25 21 37]
 [15 17 12 14 12 42  9 31  1 32 23 17 34 23 28 27  4 19 22 26 28 35 40 26
  33 21 39 12 14 39 30 27]
 [30 28 46 30  2 25 44 25 28 22 14  6  0  8  2 29 35 24 37 22 14 31 35 24
  26 34 42 13 13 34 39 37]
 [21 29 23 42 25 16  6 30 10 26 18 21 44 25 15 14 23 25 11 27 40 27 39 15
  20 33 15 16 22 29 17 15]
 [14  2  5 10 34 15  2  2 19 13  6  8 20 13 32 14 20  1 32  7 15 28 33 20
  19 30 18  8 24 18 42 37]]

In [106]:
# 同样要获取测试集的叶节点索引
gbdt_feats_test = model.predict(test, pred_leaf = True)
print(gbdt_feats_test[:5])

[[31 14  2 20  2 26 18  5 18 23  2 37 16  6 30  6  5  1 15 12 20 14  7 37
  44  2 18 44  0  5 42 37]
 [ 2 32  7  2  2  2 18 10  2 31  2  2 16 12 30 40 10 35 18 18  5  3 10 32
  41  6  2 20 47 40  0 26]
 [ 8 12 36 13 38  5 23 21 17 22 13 24  5 32 40  3  3 21  5 25  5 17  6 13
   6 23  4 33  7  8  3 20]
 [33 42 48 33  5  4 44 36 33 36 36 32 36 30  5 29 15 21  7 44 25 27 39 10
  26 15  7 33 32 19 45 17]
 [27 21 44 25 35 35 24 19 25 17 17 11 27 32 39 14 22 42 19 28 30  8 31 42
  18  7 34  6 23 43 24 11]]

### LR模型·

In [107]:
# 将 32 课树的叶节点序号构造成 DataFrame，方便后续进行 one-hot
gbdt_feats_name = ['gbdt_leaf_' + str(i) for i in range(n_estimators)]
df_train_gbdt_feats = pd.DataFrame(gbdt_feats_train, columns = gbdt_feats_name) 
df_test_gbdt_feats = pd.DataFrame(gbdt_feats_test, columns = gbdt_feats_name)
df_train_gbdt_feats

,gbdt_leaf_0,gbdt_leaf_1,gbdt_leaf_2,gbdt_leaf_3,gbdt_leaf_4,gbdt_leaf_5,gbdt_leaf_6,gbdt_leaf_7,gbdt_leaf_8,gbdt_leaf_9,...,gbdt_leaf_22,gbdt_leaf_23,gbdt_leaf_24,gbdt_leaf_25,gbdt_leaf_26,gbdt_leaf_27,gbdt_leaf_28,gbdt_leaf_29,gbdt_leaf_30,gbdt_leaf_31
0,7,15,1,14,17,7,7,15,10,16,...,0,23,22,3,8,3,6,25,21,37
1,15,17,12,14,12,42,9,31,1,32,...,40,26,33,21,39,12,14,39,30,27
2,30,28,46,30,2,25,44,25,28,22,...,35,24,26,34,42,13,13,34,39,37
3,21,29,23,42,25,16,6,30,10,26,...,39,15,20,33,15,16,22,29,17,15
4,14,2,5,10,34,15,2,2,19,13,...,33,20,19,30,18,8,24,18,42,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,35,34,33,38,40,37,0,0,0,39,...,40,0,32,19,43,0,47,25,14,23
1595,12,20,22,23,6,17,32,31,12,19,...,41,27,24,33,17,28,30,33,45,39
1596,27,9,34,35,38,35,27,19,3,24,...,37,21,10,29,34,6,23,5,24,34
1597,8,5,17,6,16,5,2,22,6,8,...,7,0,21,2,2,23,5,16,7,23
1598,33,34,39,27,40,38,44,24,0,39,...,46,47,32,19,37,46,31,21,20,40

In [108]:
train_len = df_train_gbdt_feats.shape[0]
data = pd.concat([df_train_gbdt_feats, df_test_gbdt_feats])
data

,gbdt_leaf_0,gbdt_leaf_1,gbdt_leaf_2,gbdt_leaf_3,gbdt_leaf_4,gbdt_leaf_5,gbdt_leaf_6,gbdt_leaf_7,gbdt_leaf_8,gbdt_leaf_9,...,gbdt_leaf_22,gbdt_leaf_23,gbdt_leaf_24,gbdt_leaf_25,gbdt_leaf_26,gbdt_leaf_27,gbdt_leaf_28,gbdt_leaf_29,gbdt_leaf_30,gbdt_leaf_31
0,7,15,1,14,17,7,7,15,10,16,...,0,23,22,3,8,3,6,25,21,37
1,15,17,12,14,12,42,9,31,1,32,...,40,26,33,21,39,12,14,39,30,27
2,30,28,46,30,2,25,44,25,28,22,...,35,24,26,34,42,13,13,34,39,37
3,21,29,23,42,25,16,6,30,10,26,...,39,15,20,33,15,16,22,29,17,15
4,14,2,5,10,34,15,2,2,19,13,...,33,20,19,30,18,8,24,18,42,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,4,7,1,7,13,6,5,33,7,33,...,38,25,0,20,43,11,16,25,14,26
396,0,0,33,0,40,0,43,25,27,15,...,40,33,0,4,9,18,47,0,40,0
397,10,32,4,11,6,13,41,10,20,20,...,8,12,39,49,45,2,12,47,11,22
398,15,17,12,14,1,19,1,33,1,1,...,29,25,32,21,43,12,44,22,22,32
399,32,5,42,6,20,27,2,22,6,43,...,22,45,41,35,36,36,10,36,6,31

In [109]:
# 对每棵树的叶节点序号进行 one-hot
for col in gbdt_feats_name:
    onehot_feats = pd.get_dummies(data[col], prefix = col)
    data.drop([col], axis = 1, inplace = True)
    data = pd.concat([data, onehot_feats], axis = 1)

In [110]:
data

,gbdt_leaf_0_0,gbdt_leaf_0_1,gbdt_leaf_0_2,gbdt_leaf_0_3,gbdt_leaf_0_4,gbdt_leaf_0_5,gbdt_leaf_0_6,gbdt_leaf_0_7,gbdt_leaf_0_8,gbdt_leaf_0_9,...,gbdt_leaf_31_38,gbdt_leaf_31_39,gbdt_leaf_31_40,gbdt_leaf_31_41,gbdt_leaf_31_42,gbdt_leaf_31_43,gbdt_leaf_31_44,gbdt_leaf_31_45,gbdt_leaf_31_46,gbdt_leaf_31_47
0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
396,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
397,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
398,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
399,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [111]:
train = data[: train_len]
test = data[train_len:]
train.head(5)

,gbdt_leaf_0_0,gbdt_leaf_0_1,gbdt_leaf_0_2,gbdt_leaf_0_3,gbdt_leaf_0_4,gbdt_leaf_0_5,gbdt_leaf_0_6,gbdt_leaf_0_7,gbdt_leaf_0_8,gbdt_leaf_0_9,...,gbdt_leaf_31_38,gbdt_leaf_31_39,gbdt_leaf_31_40,gbdt_leaf_31_41,gbdt_leaf_31_42,gbdt_leaf_31_43,gbdt_leaf_31_44,gbdt_leaf_31_45,gbdt_leaf_31_46,gbdt_leaf_31_47
0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [112]:
# 划分 LR 训练集、验证集
x_train, x_val, y_train, y_val = train_test_split(train, target, test_size = 0.3, random_state = 2018)
print(x_train.shape,x_val.shape,y_train.shape,y_val.shape)

(1119, 1579) (480, 1579) (1119,) (480,)

In [113]:
from sklearn import metrics
# 开始训练lr
lr = LogisticRegression()
lr.fit(x_train, y_train)

LogisticRegression()

In [114]:
# 对测试集预测
y_pred = lr.predict(x_val)

y_score = lr.predict_proba(x_val)
print(y_pred[:5])
print(y_score[:5])

[0 0 0 0 0]
[[0.9975497  0.0024503 ]
 [0.98498492 0.01501508]
 [0.83917554 0.16082446]
 [0.99785008 0.00214992]
 [0.99726549 0.00273451]]

In [115]:
y_pred.shape

(480,)

In [116]:
print(metrics.classification_report(y_val,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92       360
           1       0.87      0.62      0.72       120

    accuracy                           0.88       480
   macro avg       0.88      0.79      0.82       480
weighted avg       0.88      0.88      0.87       480

In [117]:
print(metrics.accuracy_score(y_val,y_pred))

0.88125

In [118]:
fpr, tpr, thresholds = metrics.roc_curve(y_val, y_score[:,1], pos_label=2)
print(fpr,tpr,thresholds)

[0.         0.00208333 1.        ] [nan nan nan] [1.99175008e+00 9.91750078e-01 1.37887226e-04]

/Users/edz/anaconda3/envs/aicode/lib/python3.7/site-packages/sklearn/metrics/_ranking.py:813: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  UndefinedMetricWarning)

In [119]:
metrics.auc(fpr,tpr)

nan

In [120]:
metrics.roc_auc_score(y_val,y_pred_pro[:,1])

0.9177314814814814